services:
  - mysql:5.6.14

before_script:
  - php -v && composer -V && phpunit --version
  - ps aux | grep mysql && ps aux | grep redis
  - composer install

compile:
  script:
    - cd application/tests && phpunit

after_script:
  - ps aux | grep mysql && ps aux | grep redis
